meta_product_name: "Ceramiques Nugier"
meta_title: "Ceramiques Nugier - vente de céramiques et poteries artisanales"
meta_description: "Mes céramiques sont en grès rouge. Décor composé de couleurs variées avec un émail mat et satiné. Ma production se compose de poteries utilitaires et de pièces uniques décoratives."
meta_image: "home2.jpg"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards

